image:
  repository: yarema2000
  name: food-service
  tag: 0.2

migrations:
  image:
    repository: yarema2000
    name: microservices-migrations
    tag: 0.1
  config:
    MYSQL_URL: "mysql://root:password@tcp(mysql:3306)/microservices?tls=false"
    VERSION: "20221021191933"

configs:
  DB_HOST: "mysql:3306"
  DB_NAME: "microservices"

secrets:
  DB_USERNAME: "cm9vdA==" #root
  DB_PASSWORD: "cGFzc3dvcmQ=" #password

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/food
  port: http