apiVersion: v2
type: application
version: 0.1.0
name: user-service
appVersion: "0.2"
description: "User-service for helm-demo"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common