apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: mysql          # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: mysql            # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: mysql:8.0.28      # образ Docker
          imagePullPolicy: "IfNotPresent" 
          name: mysql           # ім'я контейнеру
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim