apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-service-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: food-service               # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: food-service               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      initContainers:
        - name: run-migrations-food
          image: yarema2000/microservices-migrations:0.1
          imagePullPolicy: "IfNotPresent" 
          command: ["migrate", "-path", "/migrations", "-database", "$(MYSQL_URL)", "goto", "$(VERSION)"]
          env:
            - name: MYSQL_URL
              value: "mysql://root:password@tcp(mysql:3306)/microservices?tls=false"
            - name: VERSION
              value: "20221021191933"
      containers:
        - image: yarema2000/food-service:0.2       # образ Docker
          imagePullPolicy: "IfNotPresent"
          name: food-service           # ім'я контейнеру
          ports:
            - containerPort: 8080  # порт по якому можна звертатись до поди
          envFrom:
            - configMapRef:
                name: food-service-config
            - secretRef:
                name: food-service-secret