#spring:
#  datasource:
#    password: ${DB_PASSWORD}
#    username: ${DB_USERNAME}
#    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&sslMode=DISABLED
#  rabbitmq:
#    host: ${RABBIT_HOST}
#    username: ${RABBIT_USERNAME}
#    password: ${RABBIT_PASSWORD}

spring:
  datasource:
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/microservices?allowPublicKeyRetrieval=true&sslMode=DISABLED
  rabbitmq:
    host: localhost
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true