image:
  repository: yarema2000
  name: consumer-service-monitoring
  tag: 0.1

migrations:
  image:
    repository: yarema2000
    name: microservices-migrations-messaging
    tag: 0.1
  config:
    MYSQL_URL: "mysql://root:password@tcp(mysql:3306)/microservices?tls=false"
    VERSION: "20221021191933"

configs:
  DB_HOST: "mysql:3306"
  DB_NAME: "microservices"
  RABBIT_HOST: "rabbitmq"

secrets:
  DB_USERNAME: "cm9vdA==" #root
  DB_PASSWORD: "cGFzc3dvcmQ=" #password
  RABBIT_USERNAME: "Z3Vlc3Q=" #guest
  RABBIT_PASSWORD: "Z3Vlc3Q=" #guest

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/messages
  port: http